### ISSUE TITLE
Class RadioDNS contains declaration of RADIOEPG twice

### ISSUE THREAD

**Issue by TorstenH82** [radiodns/java-radiodns#2]
* @version 1.0.3
 */
public class RadioDNS {

	public static final String RADIOEPG = "radioepg";
	public static final String RADIOEPG = "radiospi";

Implementation of RADIOSPI seems not to be completed and radiodns-1.0.4.jar can't be integrated into project

**Comment by nickpiggott** [comment]
This was an error in the declarations section, and is corrected in new release v1.0.5, which is available now at https://github.com/radiodns/java-radiodns/tree/v1.0.5

**Comment by TorstenH82** [comment]
Thanks for the quick fix. Unfortunately it's still not possible to use the libary:

Task :app:compileDebugJavaWithJavac FAILED
error: package org.radiodns does not exist

If I replace with version 1.0.3 compilation works so I think there is still an error which prevents compilation.

Have you tried to compile the coding?

**Comment by TorstenH82** [comment]
Seems you switched to minidns whereby the Readme points to dnsjava

**Comment by TorstenH82** [comment]
Additionally 1.0.3 contains .class files. 1.0.5 are .java files. Have you missed a compilation step?

**Comment by nickpiggott** [comment]
It looks like the compilation of the .jar may not be correct. I'll get it looked at over the weekend and get a new version out first thing w/c 29th April.
